# fly.toml app configuration file generated for fly-audio-transcoder-api on 2023-09-27T00:23:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-audio-transcoder-api"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
